# Generated by Django 4.0.6 on 2022-07-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ASSTS', 'ASSTS'), ('LIABLIIES', 'LIABLIIES'), ('INCOME', 'INCOME'), ('EXPNSES', 'EXPNSES')], max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('fullcode', models.CharField(max_length=25)),
                ('parant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subacount.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invoice', 'invoice'), ('income', 'income'), ('expense', 'expense'), ('bill', 'bill')], max_length=255)),
                ('discraption', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('IQD', 'IQD')], max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subacount.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subacount.transaction')),
            ],
        ),
    ]
