# Generated by Django 4.0.6 on 2022-07-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subacount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentery',
            options={'verbose_name_plural': 'JournalEnteries'},
        ),
    ]
