# Generated by Django 4.0.6 on 2022-07-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subacount', '0002_alter_journalentery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
