# Generated by Django 4.0.6 on 2022-07-31 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subacount', '0003_account_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='discraption',
            new_name='discription',
        ),
    ]
