# Generated by Django 4.0.6 on 2022-07-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subacount', '0004_rename_discraption_transaction_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentery',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_enteries', to='subacount.account'),
        ),
    ]
