# Generated by Django 4.0.6 on 2022-07-31 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subacount', '0005_alter_journalentery_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentery',
            options={'verbose_name_plural': 'Journal Enteries'},
        ),
    ]
